"""Added minutes and hours field to standard timer. Also added validation for those fields

Revision ID: 7fe94c99316b
Revises: fd688e73cec5
Create Date: 2025-11-08 12:00:10.947137

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe94c99316b"
down_revision: Union[str, Sequence[str], None] = "fd688e73cec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("standard_timer", sa.Column("minutes", sa.Integer(), nullable=False))
    op.add_column("standard_timer", sa.Column("hours", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("standard_timer", "hours")
    op.drop_column("standard_timer", "minutes")
    # ### end Alembic commands ###
