"""improved database organization and added fields

Revision ID: b31a9a3c2339
Revises: a7ada15d9f0a
Create Date: 2025-11-11 23:36:50.057151

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b31a9a3c2339"
down_revision: Union[str, Sequence[str], None] = "a7ada15d9f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "standard_timer", sa.Column("elapsed_seconds", sa.Integer(), nullable=False)
    )
    op.add_column(
        "standard_timer", sa.Column("total_pause_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "standard_timer",
        sa.Column("last_pause_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("standard_timer", "pause_count")
    op.drop_column("standard_timer", "last_pause")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "standard_timer",
        sa.Column(
            "last_pause",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "standard_timer",
        sa.Column("pause_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("standard_timer", "last_pause_time")
    op.drop_column("standard_timer", "total_pause_count")
    op.drop_column("standard_timer", "elapsed_seconds")
    # ### end Alembic commands ###
