"""Updated standard timer model to improve flow. Added state fields, and allowed start and end time to be nullable.

Revision ID: f925504778a9
Revises: 7e3375ec20e2
Create Date: 2025-11-08 11:37:31.804585

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f925504778a9"
down_revision: Union[str, Sequence[str], None] = "7e3375ec20e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "standard_timer", sa.Column("is_started", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "standard_timer", sa.Column("is_paused", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "standard_timer", sa.Column("is_completed", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "standard_timer",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "standard_timer",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "standard_timer",
        "start_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "standard_timer",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "standard_timer",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "standard_timer",
        "start_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("standard_timer", "updated_at")
    op.drop_column("standard_timer", "created_at")
    op.drop_column("standard_timer", "is_completed")
    op.drop_column("standard_timer", "is_paused")
    op.drop_column("standard_timer", "is_started")
    # ### end Alembic commands ###
