"""Added fields to improve tracking of paused timer state

Revision ID: fd688e73cec5
Revises: f925504778a9
Create Date: 2025-11-08 11:46:41.015733

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd688e73cec5"
down_revision: Union[str, Sequence[str], None] = "f925504778a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "standard_timer",
        sa.Column("total_paused_seconds", sa.Integer(), nullable=False),
    )
    op.add_column(
        "standard_timer",
        sa.Column("last_pause", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("standard_timer", "last_pause")
    op.drop_column("standard_timer", "total_paused_seconds")
    # ### end Alembic commands ###
